Extension for Traffic Sign classification for better harmonisation with OpenDRIVE
OpenSimulationInterface/open-simulation-interface pull request #482
Opened 2021-02-11 15:16 UTC by MarcelOliver

#### Add a description
OpenDRIVE categorization for traffic signs is more generic than OSI enum. 
[OpenDRIVE 1.6](https://releases.asam.net/OpenDRIVE/1.6.0/ASAM_OpenDRIVE_BS_V1-6-0.html#_signals) definition for traffic sign:
![2021-02-11_15h02_03](https://user-images.githubusercontent.com/41865516/107646380-3111eb80-6c7a-11eb-96ec-c5359d4fb63c.png)

**Some questions to ask**:
What is this change?
Extension for traffic sign classification (mainSign and sulpplementarySign). Adding attributes **country**, **country_revision**, **code** and **sub_code** in order to provide a better traffic sign harmonisation with OpenDRIVE.

![2021-02-11_13h50_04](https://user-images.githubusercontent.com/41865516/107643729-d62ac500-6c76-11eb-9ae5-d485233c42b9.png)

#### Mention a member
@HendrikAmelunxen @pmai 

#### Check the checklist

- [ ] My code and comments follow the [style guidelines](https://opensimulationinterface.github.io/osi-documentation/osi/commenting.html) and [contributors guidelines](https://opensimulationinterface.github.io/osi-documentation/osi/howtocontribute.html) of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the [documentation](https://github.com/OpenSimulationInterface/osi-documentation).
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests / travis ci pass locally with my changes.

2021-03-25 09:58 UTC, HendrikAmelunxen approved these changes
Approved; as discussed in OSI Harmonization working group

2021-03-31 09:29 UTC, stefancyliax commented
OSI CCB:
- verify the proto comments (styling) (Pierre)
- documentation review: how should we mark deprecated parts of the code (Max)

2021-05-26 09:23 UTC, kmeids commented
**Output from CCB 26.05.2021**
1. @max-rosin please do a documentation review and set to ReadyForCCBReview when done.

2021-06-25 12:52 UTC, max-rosin requested changes

2021-06-25 12:52 UTC, max-rosin commented on osi_roadmarking.proto
> +        // or completly covering a road marking making it not visible.
Typo: "completely"...

2021-06-25 12:52 UTC, max-rosin commented on osi_roadmarking.proto
> +        // How the Type will be dealt in future will be discussed in Harmonization OpenX group.<br>
Typo: "dealt with..."

2021-06-25 12:52 UTC, max-rosin commented on osi_roadmarking.proto
> +        // Deprecated planned for version 4.0.0
Better: "Deprecation planned for..." or "Deprecated status planned for..."

2021-06-25 12:52 UTC, max-rosin commented on osi_trafficsign.proto
> +            // Deprecated planned for version 4.0.0
Better: "Deprecation planned for..." or "Deprecated status planned for..."

2021-06-25 12:52 UTC, max-rosin commented on osi_trafficsign.proto
> +            // How the Type type will be dealt in future will be discussed in Harmonization OpenX group.<br>
Typo: "dealt with..."

2021-06-25 12:52 UTC, max-rosin commented on osi_trafficsign.proto
> +            // Deprecated planned for version 4.0.0
Better: "Deprecation planned for..." or "Deprecated status planned for..."

2021-06-25 12:52 UTC, max-rosin commented on osi_trafficsign.proto
> +            // Deprecated planned for version 4.0.0
Better: "Deprecation planned for..." or "Deprecated status planned for..."

2021-06-25 12:52 UTC, max-rosin commented on osi_trafficsign.proto
> +            // Deprecated planned for version 4.0.0
Better: "Deprecation planned for..." or "Deprecated status planned for..."

2021-06-25 12:52 UTC, max-rosin commented on osi_trafficsign.proto
> +            // Deprecated planned for version 4.0.0
Better: "Deprecation planned for..." or "Deprecated status planned for..."

2021-06-25 12:52 UTC, max-rosin commented on osi_trafficsign.proto
> +            // Deprecated planned for version 4.0.0
Better: "Deprecation planned for..." or "Deprecated status planned for..."

2021-06-25 12:52 UTC, max-rosin commented on osi_trafficsign.proto
> +            // Deprecated planned for version 4.0.0
Better: "Deprecation planned for..." or "Deprecated status planned for..."

2021-06-25 12:52 UTC, max-rosin commented on osi_trafficsign.proto
> +                // Deprecated planned for version 4.0.0
Better: "Deprecation planned for..." or "Deprecated status planned for..."

2021-06-25 12:52 UTC, max-rosin commented on osi_trafficsign.proto
> +                // How the enum Direction will be dealt in future will be discussed in Harmonization OpenX group.<br>
Typo: "dealt with..."

2021-06-25 12:52 UTC, max-rosin commented on osi_trafficsign.proto
> +            // How the enum Actor will be dealt in future will be discussed in Harmonization OpenX group.<br>
Typo: "dealt with..."

2021-06-25 12:52 UTC, max-rosin commented on osi_trafficsign.proto
> +            // How the enum Type will be dealt in future will be discussed in Harmonization OpenX group.<br>
Typo: "dealt with..."

2021-06-25 12:52 UTC, max-rosin commented on osi_trafficsign.proto
> +            // How the Arrow arrow will be dealt in future will be discussed in Harmonization OpenX group.<br>
Typo: "dealt with..."

2021-06-25 12:52 UTC, max-rosin commented on osi_trafficsign.proto
> +            // How the Actor actor will be dealt in future will be discussed in Harmonization OpenX group.<br>
Typo: "dealt with..."

2021-06-25 12:52 UTC, max-rosin commented on osi_trafficsign.proto
> +            // How the Type type will be dealt in future will be discussed in Harmonization OpenX group.<br>
Typo: "dealt with..."

2021-06-25 12:52 UTC, max-rosin commented on osi_trafficsign.proto
> +            // How the Type will be dealt in future will be discussed in Harmonization OpenX group.<br>
Typo: "dealt with..."

2021-06-25 12:52 UTC, max-rosin commented on osi_trafficsign.proto
> +            // How the bool vertically_mirrored will be dealt in future will be discussed in Harmonization OpenX group.<br>
Typo: "dealt with..."

2021-06-25 12:52 UTC, max-rosin commented on osi_trafficsign.proto
> +            // How the DirectionScope direction_scope will be dealt in future will be discussed in Harmonization OpenX group.<br>
Typo: "dealt with..."

2021-06-25 12:52 UTC, max-rosin commented on osi_trafficsign.proto
> +            // Deprecated planned for version 4.0.0
Better: "Deprecation planned for..." or "Deprecated status planned for..."

2021-06-25 12:52 UTC, max-rosin commented on osi_trafficsign.proto
> +            // Deprecated planned for version 4.0.0
Better: "Deprecation planned for..." or "Deprecated status planned for..."

2021-07-01 07:44 UTC, max-rosin approved these changes

2021-07-13 08:25 UTC, ThomasNaderBMW commented on osi_roadmarking.proto
> +        // How the Type will be dealt with in future will be discussed in Harmonization OpenX group.<br>
in the future?

2021-07-13 08:30 UTC, stefancyliax commented
CCB 13.07.2021:
Review in CCB:
- Harmonization topic for "type" in relation to OpenDRIVE. Please add name of corresponding field in OpenDRIVE.
- add general hint to OpenDRIVE
- "Deprecated status planned for version 4.0.0" needs to be changed to "revision planned for version 4.0.0"
to be done by @pmai

2021-07-21 09:17 UTC, kmeids commented
**CCB Output 21.07.2021**
1. @pmai will be able to merge this.

2021-07-21 10:19 UTC, merged