Add new traffic sign variability types
OpenSimulationInterface/open-simulation-interface pull request #683
Opened 2022-11-04 10:05 UTC by thomassedlmayer

#### Description
- Clarify definition of VARIABILITY_FIXED and VARIABILITY_VARIABLE to differentiate from new types
- Add new types VARIABILITY_VARIABLE_MOVABLE and VARIABILITY_VARIABLE_MUTABLE

As already mentioned by @jdsika in #623, the differentiation between mutable content (e.g. traffic sign type) and changes in position of traffic signs is not given yet.
To maintain backwards compatibility the existing type VARIABILITY_VARIABLE is essentially kept as it is. It still describes traffic signs that CAN BE semantically and positionally variable. This means that it has to be expected that the traffic sign's type and position could change over time (exactly as it is with the current OSI version). If further differentiation in terms of semantics and position is desired, the new types VARIABILITY_VARIABLE_MOVABLE and VARIABILITY_VARIABLE_MUTABLE can be used.

#### Examples
VARIABILITY_VARIABLE:
> Pickup truck at the Autobahn carries a semantically mutable (e.g. digital) sign for a construction site which moves on the car.

VARIABILITY_VARIABLE_MUTABLE:
> Digital or analog mutable traffic signs like signs on a traffic sign gantry.

VARIABILITY_VARIABLE_MOVABLE:
> Temporary (but semantically immutable) signs at construction sites.

#### Checklist
- [x] My suggestion follows the [style and contributors guidelines](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/specification/contributing/start_contributing.html).
- [x] I have taken care about the [message documentation](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/specification/contributing/commenting_messages.html) and the [fields and enums documentation](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/specification/contributing/commenting_fields_enums.html).
- [x] I have done the [DCO signoff](https://opensimulationinterface.github.io/osi-documentation/open-simulation-interface/doc/howtocontribute.html#developer-certification-of-origin-dco).
- [x] My changes generate no errors when passing CI tests. 
- [x] I have successfully implemented and tested my fix/feature locally.
- [x] Appropriate reviewer(s) are assigned.

﻿#### References
#623 
#671

2022-11-07 10:42 UTC, pmai commented
CCB 2022-11-07: First to be further discussed in Harmonisation group, and possibly await results from dynamic signs harmonization effort.

2022-11-09 09:20 UTC, thempen commented
The enum VARIABILITY_VARIABLE is not clearly defined, if it is movable and mutable, it can be, or can't. An additional field "VARIABILITY_MOVABLE_AND_MUTABLE" will be more specific.

Movable assumes, you can have a temporary sign e.g., for road works, but also traffic signs on vehicles. @SensorWG: Do we need to distinguish between these tempory signs or signs on vehicles?

2022-11-09 09:49 UTC, pmai requested changes
Proposed changes as per harmonization discussion.

2022-11-09 09:49 UTC, pmai commented on osi_trafficsign.proto
> +        // Sign that can change semantically and positionally.
As suggested in harmonization review, switch this to be undetermined legacy value, and point to new more specififc values:

```suggestion
        // Sign that can change semantically and/or positionally, i.e.
        // it is left unspecified which of those apply. Note that this
        // represents a legacy definition, please use the more specific
        // values below, if possible, to indicate the exact nature of
        // variability.
```

2022-11-09 09:49 UTC, pmai commented on osi_trafficsign.proto
> +        VARIABILITY_VARIABLE_MOVABLE = 4;
Given the suggestion to add VARIABLE_MOVABLE_AND_MUTABLE, it is probably a good idea to drop the VARIABLE_ part for all of the new enum values:

```suggestion
        VARIABILITY_MOVABLE = 4;
```

2022-11-09 09:49 UTC, pmai commented on osi_trafficsign.proto
> +        // traffic sign on traffic sign gantry or analog prism signs.
```suggestion
        // Sign that can change semantically but not positionally, e.g.
        // digital traffic sign on traffic sign gantry or analog prism
        // signs.
```

2022-11-09 09:49 UTC, pmai commented on osi_trafficsign.proto
> +        VARIABILITY_VARIABLE_MUTABLE = 5;
```suggestion
        VARIABILITY_MUTABLE = 5;

        // Sign that can change semantically and positionally, e.g. a
        // digital traffic sign at a construction site, or a digital
        // traffic sign attached to a road works vehicle.
        //
        VARIABILITY_MOVABLE_AND_MUTABLE = 6;
```

2022-12-12 12:30 UTC, pmai approved these changes

2022-12-12 12:31 UTC, pmai commented
CCB 2022-12-12: Merge as-is.

2022-12-12 12:46 UTC, merged